# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170215_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
